[build]
  base = "traincrewhub-next"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200
  force = true

