create table if not exists public.schedule_change_events (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  actual_duty_id uuid,
  action text not null check (action in ('insert', 'update', 'delete')),
  old_duty_id uuid,
  new_duty_id uuid,
  old_employee_id uuid,
  new_employee_id uuid,
  old_assignment_role text,
  new_assignment_role text,
  changed_at timestamptz not null default now(),
  changed_by uuid
);

create index if not exists idx_schedule_change_events_schedule_date
  on public.schedule_change_events (schedule_date, changed_at desc);

alter table if exists public.schedule_change_events enable row level security;

drop policy if exists "Users can read own schedule change events" on public.schedule_change_events;
create policy "Users can read own schedule change events"
  on public.schedule_change_events
  for select
  to public
  using (
    public.is_current_user_admin()
    or (new_employee_id is not null and public.is_own_employee(new_employee_id))
    or (old_employee_id is not null and public.is_own_employee(old_employee_id))
  );

create or replace function public.log_schedule_change_event_on_actual_duty_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.schedule_change_events (
      schedule_date,
      actual_duty_id,
      action,
      new_duty_id,
      new_employee_id,
      new_assignment_role,
      changed_by
    )
    values (
      new.date,
      new.id,
      'insert',
      new.duty_id,
      new.employee_id,
      new.assignment_role,
      auth.uid()
    );

    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.date is distinct from old.date
      or new.duty_id is distinct from old.duty_id
      or new.employee_id is distinct from old.employee_id
      or new.assignment_role is distinct from old.assignment_role then
      insert into public.schedule_change_events (
        schedule_date,
        actual_duty_id,
        action,
        old_duty_id,
        new_duty_id,
        old_employee_id,
        new_employee_id,
        old_assignment_role,
        new_assignment_role,
        changed_by
      )
      values (
        coalesce(new.date, old.date),
        new.id,
        'update',
        old.duty_id,
        new.duty_id,
        old.employee_id,
        new.employee_id,
        old.assignment_role,
        new.assignment_role,
        auth.uid()
      );
    end if;

    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.schedule_change_events (
      schedule_date,
      actual_duty_id,
      action,
      old_duty_id,
      old_employee_id,
      old_assignment_role,
      changed_by
    )
    values (
      old.date,
      old.id,
      'delete',
      old.duty_id,
      old.employee_id,
      old.assignment_role,
      auth.uid()
    );

    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_actual_duties_log_schedule_change_event on public.actual_duties;
create trigger trg_actual_duties_log_schedule_change_event
after insert or update or delete on public.actual_duties
for each row
execute function public.log_schedule_change_event_on_actual_duty_change();

grant execute on function public.log_schedule_change_event_on_actual_duty_change() to authenticated;
